In [2]:
import torch
import numpy as np

In [3]:
np.random.seed(42)
torch.manual_seed(42)

In [4]:
arr = np.random.randint(0, 5, 6)
arr


array([3, 4, 2, 4, 4, 1], dtype=int32)

In [5]:
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [6]:
x = x.to(torch.int64)

In [7]:
x = x.view(3, 2)

In [8]:
right_column = x[:, 1]
right_column

tensor([4, 4, 1])

In [9]:
squared = x ** 2

In [10]:
y = torch.randint(0, 5, (2, 3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [11]:
result = torch.matmul(x, y)